version: '3.8'

services:
  service1:
    build:
      context: ./service_1
    container_name: service1
    ports:
      - "8001:8001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      retries: 3

  service2:
    build:
      context: ./service_2
    container_name: service2
    ports:
      - "8002:8002"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      retries: 3

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

